# THIS SHOULD ALWAYS BE YOUR FIRST LINE
from Myro import *
init("sim") #if your simulator is not running
penDown()
forward(2,2)
wait(.5)
turnLeft(1,1)
turnLeft(1,1)
turnLeft(1,.47)
wait(.1)
forward(2,2)
wait(.5)
turnLeft(1,1)
turnLeft(1,1)
turnLeft(1,.47)
wait(.1)
forward(2,2)
wait(.5)
turnLeft(1,1)
turnLeft(1,1)
turnLeft(1,.47)
wait(.1)
forward(2,2)